<?php
$page_title="Utilising the PIC Backup Data";
require_once("config.ini.php");
require_once("function.ini.php");

$show_key= meta_tools();
$desc = "This section explains what the very comprehensive data that forms the Performance Indicator Chart represents, and also teaches how to get the most out of that data.";

require_once("header.ini.php");

$PAGE_TITLE="Utilising the PIC Backup Data";
?>
<style>
	li {padding-bottom:8px;line-height:150%;}
	ul, ol {padding:0;margin-bottom:0px;}
</style>

<!-- startprint -->
<?php  page_header($PAGE_TITLE);?>

<p>Our "<span class="green">Performance Indicator Chart</span>" (<span class="green">PIC</span>) principally comprises two parts: (1) a coloured "display" chart followed by (2) a series of tables and other data charts showing the performance records for both teams involved in the match and the relevance (or otherwise) of our Program's algorithms to each team's performance.  </p>

<p>To fully understand what the coloured display chart in the <span class='green'>PIC</span> represents, please refer to the appropriate section under the "Services Information" menu titled <a href='thepic.php' class='prv'>"Performance Indicator Chart</a> (PIC)"; what follows below deals specifically with the very detailed workings of the <span class="green">PIC Backup Data</span> associated with each <span class="green">PIC</span>.</p> 

<p>Using the <span class="green">PIC</span> properly in conjunction with the relevant <span class="green">PIC Backup Data</span> will help you get the most out of the information on our website. Bear in mind that all the output posted on the website is generated by a very sophisticated computer Program which, in effect, is the same as having your own Program (except that we do all the hard work of updating and then testing it, to ensure that the results are optimised).</p>
 
<p>The following is therefore intended to stimulate you into analysing the data we produce in more depth. The ultimate aim, of course, is to enable you to make better betting selections.</p>

<p>First though, we want to touch on (i) the question of the best Bet Type(s) for <B>you</B> to opt for and (ii) how you can easily detect which matches appear to have the best chance of producing the results you are looking for (and which will be those matches where the two respective teams involved have the highest "Performance Reliabilities" - the predicted winner for winning and the predicted loser for losing):</p>

<ul style='padding-left:50px;padding-top:10px;'>    

<li>Bet Types - Inevitably, our Program will have better success rates for certain types of betting than for others. For example, you can rightly expect that our Home Win predictions will have a greater success rate than for Draw predictions. You can check this out for yourself by clicking on the "<B>Prediction Performance Records</B>" under the section labelled "<B>GENERAL DATA</B>" in the right-hand menus in the MEMBERS AREA. Remember though that the Odds for the two Bet Types vary significantly.</li>

<li>Performance Reliabilities - You will see this data if you go to the "<strong>Current 1X2 Reliabilities</strong>" data (under the "<strong>Current Probabilities/Reliabilities</strong>" sub-menu under the heading "<strong>PREDICTIONS DATA</strong>") in the right-hand menus in the MEMBERS AREA. Simply select the year and week you want to view the details for. </li> 

</ul>

<p style="padding-left:66px;padding-top:0;">Our advice here is to ignore those matches where the Reliabilities for BOTH teams are high AND they are both performing well (winning), as those are the types of matches where the result could easily swing either way!</p>   

<p>The reason why you need to pick the matches you are interested in up-front, before embarking on the detailed analytical work, is because you won't have time to do all the comparison work necessary to find many more than 6 matches per weekend. There is such a lot to take into consideration if you are going to do the job properly, so set yourself a realistic target from the outset!</p> 

<p>However, it would be much easier when considering your options for the best possible betting selections if you utilised the BLANK "<strong>EASE</strong>" Spreadsheet we produce! </p>  

<p>Having decided which Bet Type and matches you are interested in, you are now ready to commence the detailed analytical work. Accordingly, the sections below deal comprehensively with each aspect of the <span class="green">PIC Backup Data</span> provided to you for the specific purpose of undertaking an in-depth analysis of the performance of the two teams involved in each match:</p>

<p style="color:blue;font-weight:bold;">(1) Base Data Used by Program for Prediction</p>

<p>The Base Data compares the following key elements for each team, all of which are used in the algorithms applicable to our Program's prediction calculation process:</p>

<ol style="list-style-type:lower-roman;padding-bottom:0;padding-left:50px;">
  <li>the Win Quotient (WQ),</li>
  <li>the Scoring Ability (SA), and</li>
  <li>the Vulnerability (VU).</li>
</ol>

<p>Comparing the WQ's will tell you how strong, theoretically speaking, one team is compared to the other. A team's WQ is calculated having regard to how it generally performs at its current venue (Home or Away), modified to take account of its performance at the alternative venue. </p> 

<p>For all our predictions (both Midweek & Weekend matches), a Home team's current WQ comprises 70%  of its full Home WQ plus 30% of its full Away WQ, while an Away team's WQ comprises 70%  of its full Away WQ plus 30% of its full Home WQ. Tested over many years of historical data we have found that using this order of Home to Away WQ ratios is the best on average for the current algorithms employed by our Program.</p>

<p>A team's Scoring Ability and Vulnerability is simply a statement of the average number of goals it has scored or let in per match, calculated over the course of a full season. Allowances for the effects of relegations and promotions at the beginning of the season may tend to distort the picture in the early stages of a new season (here we are referring to the artificial data we have to create so that we can compare like with like, which might not be quite so applicable for some teams as we would like it to be). </p>

<p>Nonetheless, when making our own final betting selections independently from the Program's predictions, we tend to <I><B>compare the current Scoring Ability of one team with the current Vulnerability of the other team</B></I> to see if there is a correlation. Where there is a close resemblance between the 2 sets of figures, then we will tend to have more confidence in the Program's prediction than where there is a mismatch.</p> 

<p>Comparing the current and starting figures for the above 3 factors (WQ, SA and VU) can also reinforce or destroy the confidence level of the prediction, according to what is observed. For example, if a team's Scoring Ability has risen and its Vulnerability has dropped, then it may be stronger than the WQ is indicating; and, of course, the opposite is true. The Program's Projected WQ shows where the Program thinks the WQ will eventually end up, and we find that helps to reinforce our view as to the relative chances of the two opposing teams. </p>

<p style="color:blue;font-weight:bold;">(2) Program's Probabilities for Possible Outcomes</p>
<p>The Program derives the Probabilities for the Home Win, Draw and Away Win predominantly based on the respective WQ strengths of the two teams. The greater the difference between the Home Win versus the Away Win Probabilities, the stronger our faith would be in the Win prediction for the stronger team.</p>

      
<p style="color:blue;font-weight:bold;">(3) Program's Rank No for Prediction this Week</p>
<p>Our Program sorts the predictions into a hierarchy for final selection purposes within each of the Result Types (Home Wins and Away Wins). The higher the ranking of a match is, the stronger our confidence will be in our Program's prediction. </p>

<p style="color:blue;font-weight:bold;">(4) Program's Goal Prediction Accuracy this Season </p> 
<p>This portion is to help us with the final selections for Correct Scores betting. What we look for here is how close our Program is with its goal prediction accuracy for each team (or how far off the mark it is). If the figures are close, then we would be more comfortable with the Program's Correct Scores prediction than where there is a large discrepancy in the number of predicted goals.</p>
 
<p>Having said that, <B>our Program's ability to hit the correct score-line directly on the head is not high</B>, simply because there are so many "common" score-lines. We therefore cannot take the anticipated score-line at face value, and <B>it is essential to take all the other available factors into account</B> when deciding upon the most appropriate score-line to bet on.</p>
 
<p style="color:blue;font-weight:bold;">(5) Program's Overall Prediction Result Correctness this Season </p> 
<p>This area of the data sheet deals with the prediction success rate for the matches played so far this season; there is no start-of-season artificial data used here. The total number of matches actually played up to the end of the week preceding the date of the current match prediction can be seen in the extreme left-hand box for the Home team and the extreme right-hand box for the Away team. </p>
 
<p>The "CS" portion tells us how well the Program did with getting the Correct Scores predictions right for each of the teams, while the "CR" portion shows us how many times it got the Result Type (Home, Draw or Away call) right. </p>

<p>In addition, the "CR+GF" portion lets us know how many times the Program got the "Result Type" right <B>and at the same time</B> got the exact number of "Goals For" right.</p> 

<p>The final piece of information in this portion (the "Too Hi/Lo" figures) tells us how many times the Program was too high in its expectations of a team and how many times it gave the team too little credit for its ability (too low). </p>

<p>The Hi/Lo data has to be considered in the light of how many matches have been played. Where, for example, 15 current matches have been played by a team and the Program predicted too high on say 2 occasions and too low also only twice, then we would have a lot of confidence in the prediction. On the other hand, if 15 current matches had been played and the Program predicted too high on 5 occasions and too low on another 3 occasions, we would have much less confidence in the latest prediction. </p>
 
 
 <p style="color:blue;font-weight:bold;">(6) Head-to-Head</p>
<p>Where the Head-to-Head results are surprising and don't seem to have any correlation to the apparent relative strengths of the respective teams, it can often highlight the existence of a "needle/grudge match" situation or a "local derby" you weren't aware of (and they exist in every country, believe us). Where such inconsistencies occur we have found it is best to ignore those particular matches for betting purposes.</p>


<p style="color:blue;font-weight:bold;">(7) Current Season's Results to Date</p>
<p>This table is useful for checking (i) how the team is doing so far this season, match-by-match and (ii) how our Program's predictions stack up both overall and in respect of Correct Scores forecasting. Where the Anticipated Score-Line fluctuates dramatically from the actual score-line for any one of the teams, then it would be best to abandon all thoughts of placing Correct Score bets, as even utilising hedge betting across 3 alternative score-lines would probably not have much chance of success. </p>

<p>Correct Scores betting is much more successful where the actual results for both teams have proved to be reasonably close a good deal of the time to our Program's Anticipated Score-Lines, and even there hedge betting is still far more preferable than plumping for just the one score-line.</p>


<p style="color:blue;font-weight:bold;">(8) Prediction Accuracy This Season (for each individual team)</p>
<p>This information lets you know precisely what happened to our Program's calls. For example, where our Program predicted Home Wins for a team it shows us just how many of those matches actually resulted in Home Wins or ended up as Draws or Away Wins (both in pure numbers and as a percentage of all Home Win calls). This data lets you see the reliability/unreliability of the past predictions, and if the unreliability is high it simply indicates that the team plays erratically and that, in turn, our Program's base prediction shouldn't be relied upon!</p>
    

<p style="color:blue;font-weight:bold;">(9) Frequency of Goals For/Against (Current)</p>
<p>These two tables present the same score-line records in completely different ways so that you can get the fullest possible picture as to what the most common score-lines for each team have been up to the date of the current match. </p>

<p style="color:blue;font-weight:bold;">(10) Average Chances for Exact Score Possibilities</p>
<p>This table is to assist you with what the best "hedging" possibilities are for Correct Scores betting. It shows you what the 4 most common score-lines are compared to our Program's Anticipated Score-Line (ASL) for the given match. If the past ASL's for both teams have been reasonably close to the actual score-lines (and, of course, you need to check that out by looking at the "Current Season's Results to Date"), then you will most likely have identified a good opportunity for successful Correct Scores hedge betting.        </p>


<p style="color:blue;font-weight:bold;">(11) Goals Advantage</p>
<p>This chart needs to be read in conjunction with the table which follows it titled "Likelihood of Goal Difference for [<em>1-0 or whatever</em>] Prediction". If the overall prediction reliabilities for the two teams are reasonable, with a close correlation evidenced between the overall "goals for" and "goals against" predictions and the actual score-lines, then this data will be useful for Asian Handicap betting for that particular match. If there is no such correlation for one of the teams then beware, because it means that the team is erratic in its performance and thus the predicted goal advantage may be unreliable. </p>
 
<p>However, you need to consider which way the apparent difference swings, as it may be in your favour and serve to reinforce the reliability of the predicted "goal advantage". In all cases, treat the "goal advantage" figure with caution until you have tested it against all other available parameters.</p>
        
<p style="color:blue;font-weight:bold;">(12)  Incidence of Results </p>
<p>This chart displays the data for both this season and the previous season, so you can get some understanding of how each team's current performance lines up with last season's.</p>

<p>Specifically, if you see that a team is doing about the same overall this season as last season but yet, for example, the Home results have been far better than expected to date, you can anticipate that a "correction" is imminent (meaning they will probably very soon start a run of losses at Home). We would take the line that we should not push our luck in such cases, and we would then look for another team to add to our preferred betting options that week, despite the fact that, based purely on statistics, our Program may have ranked it among the "prime" selections.         </p>
         
<p style="color:blue;font-weight:bold;">(13) Current Season's Prediction Reliabilities</p>
<p>The Reliability referred to is the Program's "General Prediction Reliability", which is simply the number of correct calls made for the venue where this week's match will take place (Home or Away) compared to the total number of calls made so far this season for that venue, expressed as a percentage.</p>

<p>Our Program is set to bring forward the previous season's reliabilities for all teams except those teams relegated or promoted at the end of the previous season's play, which are then all allocated a pre-set maximum Reliability value of 30%. Where teams remain in the same Division, the starting level of the Reliability will match the closing level shown in the appropriate "Last Season's Prediction Reliabilities" chart which then follows.      </p>
     
<p>As each week's matches are played, the Reliabilities are updated, based on the reliability displayed by the particular team over the past 10 matches. The chart shows how many matches have been played at the specific venue so far this season.  </p>
  
<p style="color:blue;font-weight:bold;">(14) Last Season's Prediction Reliabilities</p>
<p>These charts show how each respective team performed last season (<strong>in whatever Division they were in</strong>) compared to the predictions, where the Reliability employed is still the "General Prediction Reliability". From this information you will clearly see which teams were reliable and which teams were unreliable for our betting purposes last season.    </p>
    
<p>Of course, prediction accuracy/reliability must be viewed as a relative concept, because you can't expect any team at all to do exactly as is expected (this is soccer, remember). So what you are looking for are those matches where the combined accuracies/reliabilities in respect of past predictions are the highest.</p>

<p style="color:blue;font-weight:bold;">(15) Other Past Season Information </p> 
<p>This information is the only additional data you will have to go on for the first few weeks of a new season.  It comprises detailed "Result Type" accuracy and "goals for" and "goals against" accuracy, plus all the detailed match outcomes (including comparisons with the Anticipated Score-Lines), all of which have been dealt with in detail above.   </p>
  
<p>In essence, they are the same tables as are used for the current season, except that they are for the full set of matches played last season and may therefore not be so relevant. One of the major things that makes the data not so reliable is that most Divisions below the Premier Divisions have 3 teams departing and 3 new entries for the current season. That means only 75% at most of the original data is still applicable, plus the close-season player transfers/acquisitions can dramatically change a team's ability. So you should use this data with caution.      </p>
      
<p>Of course, as the season progresses and more matches have been played, this outdated information becomes far less relevant. But at the start of the season you will probably be glad you have it available to you!</p>

<p style="color:blue;font-weight:bold;">(16) Additional Information to Consider </p> 
<p>Our <span class="green">PIC's</span> and the associated backup data, though very good, do not give the full story - not by a long way! So please bear in mind the following:</p>

<ol style='padding-left:50px;'>
  <li>In the early part of the season the <span class="green">PIC's</span> have only a limited function, but they become more and more useful as the season progresses.</li>

  <li>Our Program's output is based on how each team performs ON AVERAGE over a given period; it does not take the absence of specific players into account, whether through injuries or any other reason. So do please check out the latest news to see if there are reports on current injuries/absences, and take that info into account properly when making your final betting selections.</li>

  <li>Some matches defy logic when looking at the relative strengths of the teams, and a better team may often lose quite consistently to the poorer team. As we said earlier, this often happens with "grudge" or "needle" matches, especially "local derby" matches. To see for yourself whether this may apply to a match you are interested in betting on, check out the Head-to-Head stats in particular.</li>

  <li>Always check the weather expected for the day of the match, particularly if you are betting on the Correct Scores. The general rule here is that wet weather will mean fewer goals in a game where teams are evenly matched, but if one side is at Home to a decidedly weaker team in bad weather conditions, then the Away Team will often get hammered. Our final selections postings haven't taken the weather into account!</li>

  <li>Betting consistently on the Short Odds matches (where the Decimal Odds offered are a maximum of 1.50) will never make you rich and, if you do not bet wisely, could result in you losing more than you make. So don't rely on the Bookies' views as to the most likely winners! For the proof,  <a class="prv" href="javascript:Matrix('short_odds_summary.php?season=2014-2015')">check here</a>.</li>  

</ol>

<p>Please don't forget that if you look back at the <span class='green'>PIC</span> for a previous week, all reports AFTER the "PREDICTION BACKUP & USEFULNESS DATA" (i.e. from "Prediction Accuracy This Season for Home Team" on and downwards) will require_once all the FIXTURES and RESULTS information right up to the current week (due to storage space limitations on the server, because the data involved is huge - sorry about that).</p>




<!-- stopprint -->
<?php  
	$ptopic="ggexplained.php"; $ntopic="compilingpic.php";
	$msg=$PAGE_TITLE;
	require_once("icons.ini.php") ;
	require_once("footer.ini.php"); 
?>
