<?

include("config.ini.php");
include("function.ini.php");
$page_title ="Legal/Disclaimer";

include("header.ini.php");
page_header("Legal/Disclaimer") ; 

?>

<p>The principal aim of this website (www.soccer-predictions.com) is to provide useful data and information centred on what our "Predict-A-Win" computer Program predicts will be the result of up-coming football/soccer matches, although no guarantee is given that the predicted outcomes will be realised. Primarily, therefore, the prediction data and other information provided on this website is intended to serve as a guide for those wishing to check against their own assessment of the likelihood of the match outcomes.  </p>

<p>The content under this Legal/Disclaimer section of this website, along with the content of the Privacy Policy, Commenting Rules, Copyright and Refund Policy sections on this website (which every user shall be deemed to have fully read and understood), shall collectively be deemed to represent the <b>Terms and Conditions</b> that govern the use of this website, whether or not the user becomes a Registered Member hereof.  By extension, by accessing the data and information on this website it shall therefore be deemed that the user has accepted these Terms and Conditions in full and agrees to be bound by them.</p>

<p>For the purposes of interpreting the intention of all written content on this website, please note that the words "we", "us" and "our" all refer to BetWare Ltd (a Hong Kong registered company), while the words "you", "your" and "user" all refer not just to our Registered Members (whether or not they are Subscribing Members) but to all other users/visitors to this website as well. </p>

<p>To become a Registered Member on this website you must be at least 18 years old, and by so registering you shall be deemed to have represented and warranted that you have the right, authority and capacity to become a Registered Member and will abide by all of the Terms and Conditions stated herein.</p>

<p>Whilst we endeavour to ensure that the data and information on this website is correct, we do not warrant its completeness or accuracy or that it is up-to-date.  Further, by using the data and information on this website it shall be deemed that you do so in full knowledge that such usage is entirely at your own risk, and we shall not be held liable in any way in respect of the data or information that is available on this website or on any other websites to which this website has links. You shall be deemed to be aware that we do not endorse any websites that are linked to from this website, nor do we have any responsibility for the content of those websites (including the terms and conditions or privacy policies of any such websites).</p>

<p>To the maximum extent permitted by law, we exclude all representations, warranties and conditions (including, without limitation, the conditions implied by law of satisfactory quality, fitness for purpose and the use of reasonable care and skill).</p>

<p>Under no circumstances shall we be liable to you or any third party for any direct, indirect, consequential, exemplary, incidental, special or punitive damages, including any loss of profit, contracts, business, goodwill, data, income, revenue or anticipated savings arising from your use of this website, whether arising in tort, contract, or otherwise, even if we have been advised of the possibility of such damages. Should any action taken against us be found valid by any competent Court, we shall be liable to you only to the value of the last amount you paid to us, regardless of the form of the action, and regardless as to where the action was instigated from.</p>

<p>Under no circumstances shall we be held liable for any loss or damage, including personal injury or death, resulting from anyone's use of this website or use of any website to which this website has links, or for any content posted on this website or those other websites transmitted to Registered Members, or which results from participating or downloading materials in connection with this website or other linked websites or from any interactions between users of this website and other linked websites, whether online or offline.</p>

<p>We reserve the right to terminate the membership of any Registered Member for any reason whatsoever.  If such termination is effected due to a breach by you of the Terms and Conditions of this website, then no refund of subscription will be due to you.  If termination is effected for any other reason, then a refund will be paid to you based on the date of such termination. We undertake not to terminate your Membership maliciously.</p>

<p>All Registered Members are provided with a user ID and password to enable them to access restricted areas of this website's content and services, which we shall be free to disable at our sole discretion. You must ensure that your user ID and password are kept confidential, and you shall be deemed to have accepted responsibility for all activities that occur under your user ID and password.</p>

<p>Our data has been compiled, to the best of our ability, on a purely statistical basis; subjectivity has been eliminated as much as possible but not completely. Our Program's predictions are premised on what, in theory, the teams should ordinarily be capable of achieving. Inevitably there is a margin of error within each of our Program's predictions, even if the teams were to play largely as expected. However, due to the very varied randomness with which some teams perform, even that margin of error itself can fluctuate dramatically from match to match. Added to that, the human content of sports matches is such that there are many personal issues that could affect the outcome of a match. Not least is the question of the actual composition of the team on the day, as key players could be unavailable for reasons ranging from personal injury/health matters through to compelling family issues. And, of course, there are two teams to consider in the equation, not just the one!</p>

<p>We undertake to use our best endeavours to ensure the accuracy of the base data we provide (Date/Time of Fixtures, Match Results, League Tables, Odds and the like), but we give no guarantees that such data is correct. If errors are notified to us we will correct them as soon as we can.  </p>

<p>There are no sure-fire winners when it comes to betting on the results of soccer matches (or, for that matter, on any team sport). It has been observed many times, throughout each and every season, that teams that were considered invincible have fallen to teams thought to be far weaker. Added to this is the fact that the general level of the Odds offered by Bookies (Fixed Odds and Correct Scores Odds) are slanted very much in the Bookies' favour, which means that very few bettors are able to make a living from soccer betting.</p>

<p>In short, as we make clear here and elsewhere on this website, you alone are entirely responsible for deciding for yourself how much reliance, if any, you wish to place on the predictions data and other information you view on our website or as may be emailed to you from time to time. We do not give any guarantees or warranties in respect of our Services, and we shall not be held responsible for any losses that you may suffer or claim to have suffered as a result of using the data or other information displayed on this website or emailed to you. Accordingly, if you access the data and other information on this website or accept emailed data and/or information from us, you shall be deemed to have done so knowing full well the substance of this disclaimer and having accepted (i) the substance and import of this limitation of liability on our part, (ii) that we do not offer advice regarding any action you should take in respect of the data and information we post or email to you, and (iii) that you yourself are entirely and solely responsible for any betting decisions you may make and for any losses that you may thereby suffer, whether or not your bets were based on the data and other information on this website or emailed to you by us.</p>

<p>Further, we shall not be held responsible in the event that any products or services we promote do not meet the requirements of or produce the results hoped for by you, nor shall we be held liable for any adverse impacts that may arise for you when using such products or services. Any complaints, etc. or demands for refunds, etc. in respect of such services or products must therefore be taken up by you with the provider of such product or services and not addressed to us.</p>

<p>We will only ever use well-known and reputable merchant bankers to take your subscription payments, and they all generally use cookies. Advertisers may also have access to our website, and they may send you cookies and use web beacons. These third-party ad servers or ad networks use technology in the advertisements and links to send advertisements directly to your browsers, which allows them to measure the effectiveness of their advertisements and/or to personalize the advertising content that you see. We have no access to or control over such cookies that are used by third-party advertisers, and you should consult the respective privacy policies of those third-party ad servers for more detailed information on their practices as well as for instructions about how to opt-out of receiving cookies and the like.  You are also hereby referred to the Privacy Policy section of this website if you wish to know more about cookies and the like used in conjunction with this website. </p>

<p>The Terms and Conditions of this website shall be governed by and construed in accordance with English law, and any cases brought by you against us, including disputes, shall be subject to the exclusive jurisdiction of the courts of England and Wales. </p>

<p>Should any part of the Terms and Conditions of this website be held to be invalid or unenforceable, the remainder of the Terms and Conditions of this website shall remain valid and enforceable.</p>

<p>By using this website in any way you shall be deemed to have been fully aware of and fully understood the Terms and Conditions applying to such usage as specified above, whether or not you are a Registered Member, and to have accepted by such usage of the data and information on this website all such Terms and Conditions.</p>



<? include("footer.ini.php"); ?>